spring.application.name=TaskTimeTracker
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/cdek}
spring.datasource.username=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
secret.key=4826a13f170a0c15a7150b78c1f66720c5a7944011cf465a16b606a737ab7b5d
mybatis.type-handlers-package=com.tasktimetracker.handler
springdoc.use-fqn=true
mybatis.configuration.map-underscore-to-camel-case=true